.travis.yml, README.md
close #17
-
* badge now links to Travis
* run node on latest
* run check-security
* run lint
* run CI against master only
=> CI improvements

.babelrc, .travis.yml, docs/contributing.md, package-lock.json, package.json
- added travis parallel jobs
- remove duplicated node definitions
- replaces nsp with audit
- removed cpx as I couldn't fix it to be used
- renamed some tasks so that they are grouped together
- removed check security for push as it's expensive
- added trusted distribution
- addressed audit problems that were found
- updated package-lock
- removed babel as I don't think it's used
=> Travis and package optimizations

package/v1/pushButton/style.js, stories/concepts/aboutPages/welcomePage/fakeLocale.ts, stories/concepts/aboutPages/welcomePage/theme.ts
Very tiny style and grammatical updates. Coding might not be optimal structure.
=> Small style updates

src/components/index.ts, src/features/rewards/index.ts, src/old/index.ts
=> Adds missing exports

.storybook/webpack.config.js, package-lock.json, package.json
Before
After
You need to use this syntax to get correct naming https://github.com/brave/brave-ui/wiki/Code-style-guide#styled-component-definition
=> Adds styled components names into class names

src/features/rewards/panelWelcome/style.ts
=> Adhering opt-in to styled components guide

package-lock.json, package.json, tools/createComponent.js, tools/lib/templates.js
This should hopefully make kicking off a new component a bit easier.
Baseline usage is:
`npm run create NewComponent` where `NewComponent` is whatever you'd like the React Component to be named. (Note: the default folder is `src/components`, the folder that will be made here is camel cased like `newComponent`
If you want to create the component inside features, you may run:
`npm run create NewComponent rewards` or `npm run create NewComponent newFeature`
This will create a component with a basic style, index, and spec file, as well as an assets and snapshot folder. `npm run lint` and `npm run test-unit` should pass and create snapshot respectively after running this script.
=> Adding NPM script for creating a new component

src/features/rewards/amount/__snapshots__/spec.tsx.snap, src/features/rewards/amount/index.tsx, src/features/rewards/amount/style.ts
contenteditable to be used by Publishers app.
=> Add a span around the numeric value for Donation amount. This allows for

src/features/rewards/panelWelcome/__snapshots__/spec.tsx.snap, src/features/rewards/panelWelcome/index.tsx, src/features/rewards/panelWelcome/style.ts, src/features/rewards/welcomePage/__snapshots__/spec.tsx.snap, src/features/rewards/welcomePage/index.tsx, src/features/rewards/welcomePage/style.ts
=> Using heading component for rewards

src/features/rewards/index.ts, src/features/rewards/tooltip/__snapshots__/spec.tsx.snap, src/features/rewards/tooltip/index.tsx, src/features/rewards/tooltip/spec.tsx, src/features/rewards/tooltip/style.ts, stories/features/rewards/other.tsx
=> Adding Tooltip component

src/components/formControls/select/index.tsx, src/components/formControls/select/style.ts, src/features/rewards/walletPanel/index.tsx, src/features/rewards/walletWrapper/__snapshots__/spec.tsx.snap, src/features/rewards/walletWrapper/style.ts
Fixes: #112 
Before:
After with `fullWidth={true}`:
=> Adding showAllContents prop to Select

src/components/formControls/toggle/index.tsx, src/components/popupModals/modal/index.tsx, src/features/rewards/box/index.tsx, src/features/rewards/mainToggle/index.tsx, src/features/rewards/modalBackupRestore/index.tsx, src/features/rewards/walletSummary/__snapshots__/spec.tsx.snap, src/features/rewards/walletWrapper/index.tsx
Adding test-ids for rewards testing.
=> Added test ids for toggle and rewards maintoggle

src/features/rewards/box/__snapshots__/spec.tsx.snap, src/features/rewards/box/index.tsx, src/features/rewards/box/style.ts, src/features/rewards/modalActivity/__snapshots__/spec.tsx.snap, src/features/rewards/tableContribute/index.tsx, stories/assets/locale.ts
=> Addin tooltips to rewards

src/features/rewards/box/__snapshots__/spec.tsx.snap, src/features/rewards/box/style.ts
make sure that box switching on settings rewards page is working correctly now
=> Fixes box switch

src/features/rewards/box/index.tsx, stories/features/rewards/settings/contributeBox.tsx, stories/features/rewards/settings/fakeLocale.ts
- also sync settings with core
=> Shows only disabled state when box disabled

src/components/formControls/radio/__snapshots__/spec.tsx.snap, src/components/formControls/radio/index.tsx, src/components/formControls/radio/spec.tsx, src/components/formControls/radio/style.ts, src/components/index.ts, stories/components/formControls.tsx
Fixes: #174 
Concept shown here:
**Note: As Radio buttons are stilled marked WIP in the design spec, a pixel perfect match has not been done with this concept. It's pretty close but this will unblock us on adding the mobile selection option for android UI.**
=> Adding Radio button component

src/features/rewards/walletSummary/__snapshots__/spec.tsx.snap, src/features/rewards/walletSummary/index.tsx, src/features/rewards/walletSummary/spec.tsx, stories/features/rewards/concepts.tsx, stories/features/rewards/settings/pageWallet.tsx, stories/features/rewards/wallet.tsx
- removes total line
- add logic that last element doesn't have border at the bottom
=> Removes total and add optional ac

src/components/icons/loader.tsx, src/features/rewards/welcomePage/__snapshots__/spec.tsx.snap, src/features/rewards/welcomePage/index.tsx, stories/assets/locale.ts
check that when you are on welcome page and if you click on a button you get loader with creating wallet text button
=> Add loader to welcome page

src/features/rewards/hero/__snapshots__/spec.tsx.snap, src/features/rewards/hero/style.ts, src/features/rewards/infoCard/style.ts, src/features/rewards/welcomePage/__snapshots__/spec.tsx.snap, src/features/rewards/welcomePage/index.tsx, src/features/rewards/welcomePage/style.ts, stories/features/rewards/concepts.tsx
This makes the welcome page responsive in a sensible way.
For testing:
1. Navigate to the Mobile WelcomePage concept in the storybook
2. View the concept in full screen mode (CTRL + Shift + F)
3. Using the browser's dev tools, size down the concept progressively
4. Ensure that it breaks down in a way that makes sense, no clipping, looks good at all intervals etc (Particularly ensure that the info cards break down in to a single column)
5. Try it out using a few of the devices in dev tools.
6. Ensure the desk top view did not change.
Note: Styling may need tweaking if mobile design differs greatly
=> Adds mobile concept for Rewards WelcomePage

src/features/rewards/siteBanner/__snapshots__/spec.tsx.snap, src/features/rewards/siteBanner/style.ts, stories/features/rewards/concepts.tsx
… instead of fixed position as per https://github.com/brave/brave-core/pull/556
=> Allow donation dialog to auto-size height with normal DOM layout flow

src/components/formControls/toggle/__snapshots__/spec.tsx.snap, src/components/formControls/toggle/style.ts, src/features/rewards/mainToggle/__snapshots__/spec.tsx.snap, src/features/rewards/tip/__snapshots__/spec.tsx.snap, src/features/rewards/toggleTips/__snapshots__/spec.tsx.snap, src/features/rewards/walletPanel/__snapshots__/spec.tsx.snap, src/features/shields/icons/index.ts, src/features/shields/toggle/style.ts, src/features/shields/wrappers/index.ts
- adjusted the toggle component (in both shields and base) down to a more reasonable circle size for the large toggle, added a very subtle shadow, small animation tweak
- adjusted disabled state in shields where the content was looking weighted too far to the left
=> Toggle Tweak & Alignment Tweak

src/features/rewards/list/__snapshots__/spec.tsx.snap, src/features/rewards/list/index.tsx, src/features/rewards/list/style.ts, src/features/rewards/mobile/boxMobile/__snapshots__/spec.tsx.snap, src/features/rewards/mobile/boxMobile/index.tsx, src/features/rewards/mobile/boxMobile/spec.tsx, src/features/rewards/mobile/boxMobile/style.ts, src/features/rewards/mobile/index.ts, src/theme/brave-default.ts, src/theme/theme-interface.ts, stories/assets/locale.ts, stories/features/rewards/other.tsx
Fixes: #172 
The concept can be viewed using the mobile inspector under Feature Components > Rewards > Other > Mobile > Box
A GIF preview can be viewed here:
https://i.imgur.com/4Uw3tqW.gifv
The box is basically the control wrapper that will house settings details like the contribution table, viewed adds etc.
=> Adds mobile Box component, concept

src/components/buttonsIndicators/button/index.tsx, src/features/rewards/walletPanel/index.tsx, src/features/rewards/walletSummary/index.tsx, src/features/rewards/walletSummarySlider/index.tsx, src/features/rewards/walletWrapper/index.tsx, src/theme/theme-interface.ts
This PR removes unnecessary commas which should be semicolons technically.
=> Remove unnecessary comma

src/components/formControls/radio/style.ts, src/components/formControls/select/style.ts, src/features/rewards/mobile/boxMobile/__snapshots__/spec.tsx.snap, src/features/rewards/mobile/boxMobile/style.ts, src/features/rewards/mobile/index.ts, src/features/rewards/mobile/settingsPageMobile/__snapshots__/spec.tsx.snap, src/features/rewards/mobile/settingsPageMobile/index.tsx, src/features/rewards/mobile/settingsPageMobile/spec.tsx, src/features/rewards/mobile/settingsPageMobile/style.ts, src/features/rewards/mobile/walletInfoHeader/__snapshots__/spec.tsx.snap, src/features/rewards/mobile/walletInfoHeader/style.ts, src/features/rewards/tableContribute/index.tsx, src/features/rewards/tableContribute/style.ts, src/theme/brave-default.ts, src/theme/theme-interface.ts, stories/features/rewards/concepts.tsx, stories/features/rewards/settingsMobile/adsBoxMobile.tsx, stories/features/rewards/settingsMobile/contributeBoxMobile.tsx, stories/features/rewards/settingsMobile/donationsBoxMobile.tsx, stories/features/rewards/settingsMobile/fakeLocale.ts, stories/features/rewards/settingsMobile/settingsMobile.tsx, stories/features/rewards/settingsMobile/style.ts
Fixes #179 
This adds the Mobile Settings Page concept under Feature Components > Rewards > Concepts > Mobile > Settings
This should be viewed with the mobile emulator available within dev tools.
=> Adds Mobile Settings Page

src/features/rewards/mainToggle/__snapshots__/spec.tsx.snap, src/features/rewards/mainToggle/index.tsx, src/features/rewards/mainToggle/style.ts
Visual things to review:
_Consistent 18px top and bottom padding with rest of height defined by tallest item (bat logo told to have 66px height)_
In fact this also reduces the top margin of the 'off' content to the same 18px padding as the box. Possibly not desired @jenn-rhim ?
_note that the logo **is** actually centered_
=> Vertical center Rewards MainToggle title content

src/features/rewards/index.ts, src/features/rewards/tab/__snapshots__/spec.tsx.snap, src/features/rewards/tab/index.tsx, src/features/rewards/tab/spec.tsx, src/features/rewards/tab/style.ts, src/features/rewards/walletSummary/__snapshots__/spec.tsx.snap, stories/features/rewards/other.tsx
=> Adds new 2 state tab component

src/features/rewards/siteBanner/index.tsx, stories/features/rewards/concepts.tsx
Will be used for https://github.com/brave/brave-browser/issues/1924
=> Adds name to site banner

src/features/rewards/siteBanner/index.tsx, src/features/rewards/siteBanner/style.ts
=> Moves logo into bg so that we can adjust size

package-lock.json
=> fix vulnerabilities found by npm audit

src/features/rewards/amount/__snapshots__/spec.tsx.snap, src/features/rewards/amount/index.tsx, src/features/rewards/amount/style.ts, src/features/rewards/donate/__snapshots__/spec.tsx.snap, src/features/rewards/donate/index.tsx, src/features/rewards/donate/style.ts, src/features/rewards/siteBanner/__snapshots__/spec.tsx.snap, src/features/rewards/siteBanner/index.tsx, src/features/rewards/siteBanner/style.ts, src/features/rewards/tip/__snapshots__/spec.tsx.snap, stories/features/rewards/concepts.tsx
Fixes: #254 
Note: A new component was not created for this, as layout did not really need to change, just styles.
Now Link: https://brave-ui-awdllyyigp.now.sh
(Use the mobile inspector and view at **Feature Components > Rewards > Concepts > Mobile > Site Banner**)
In Action:
=> Mobile siteBanner

stories/features/rewards/settings/fakeLocale.ts, stories/features/rewards/settingsMobile/fakeLocale.ts
Fixes #256 , our storybook should be caught up with the current browser
=> Changes Donations -> Tips

src/components/formControls/select/index.tsx, src/components/formControls/select/style.ts, src/features/rewards/grantComplete/__snapshots__/spec.tsx.snap, src/features/rewards/grantComplete/index.tsx, src/features/rewards/grantComplete/style.ts, src/features/rewards/profile/__snapshots__/spec.tsx.snap, src/features/rewards/profile/index.tsx, src/features/rewards/profile/style.ts, src/features/rewards/tableContribute/index.tsx, src/features/rewards/walletPanel/__snapshots__/spec.tsx.snap, src/features/rewards/welcomePage/__snapshots__/spec.tsx.snap, src/features/rewards/welcomePage/style.ts, stories/features/rewards/settingsMobile/contributeBoxMobile.tsx, stories/features/rewards/settingsMobile/grantMobile.tsx
Fixes:
https://github.com/brave/browser-android-tabs/issues/827
https://github.com/brave/browser-android-tabs/issues/828
https://github.com/brave/browser-android-tabs/issues/829
https://github.com/brave/browser-android-tabs/issues/842
=> Android UI Fixes

src/features/rewards/tipsMigrationAlert/index.tsx, src/features/rewards/tipsMigrationAlert/style.ts
Fixes comment per: https://github.com/brave/brave-core/pull/926#issuecomment-440722539
Change pictured:
=> Adjusting modal button spacing

package.json
=> Updating package.json version to 0.34.4

src/features/rewards/siteBanner/__snapshots__/spec.tsx.snap, src/features/rewards/siteBanner/style.ts
Pictured fix:
Expected result:
=> Restores monthly alignment on desktop

src/features/rewards/siteBanner/index.tsx, stories/features/rewards/concepts.tsx
Related to: https://github.com/brave/brave-browser/issues/2238
=> Adding provider support to siteBanner

.github/pull_request_template.md
Checklist for npm publish or branch integration
Obviously this PR does not require integration
=> Create a pull request template for integration process

stories/features/sync/enabledContent.tsx, stories/features/sync/modals/scanCode.tsx, stories/features/sync/page.tsx, stories/features/sync/page/fakeData.ts
Changed some values and styles to match brave-core so we can check what's wrong here.
Sync interface should be exactly like Sync in brave-core
-  https://brave-ui-mnbepzxa3.now.sh
=> match sync interface with brave-core

src/features/rewards/walletWrapper/index.tsx
=> Adds already claimed status for the grant

src/features/newTab/default/clock/index.tsx, src/features/newTab/default/notification/index.ts, src/features/newTab/default/page/index.ts, src/features/newTab/default/topSites/index.ts, stories/features/newTab/default/index.tsx, stories/features/newTab/fakeLocale.ts, stories/old/views.story.tsx
My storybook run command was failing, this fixed it for me.
=> Fix clock component path

tools/icon-component-generator/README.md
=> Add example to icon-generator readme

src/features/rewards/box/index.tsx, src/features/rewards/box/style.ts
- we need to show coloured title all the time
- 
=> Fixes title when box is disabled

src/features/newTab/private/page/index.ts
sibling PRs https://github.com/brave/brave-ui/pull/377, https://github.com/brave/brave-ui/pull/376
=> fix private tab page height

package-lock.json
`npm run audit --fix`
`npm audit`
**_Will wait for a feature PR to move to brave-core, unless needed otherwise_**
=> security audit fix

src/features/rewards/listToken/__snapshots__/spec.tsx.snap, src/features/rewards/listToken/style.ts, src/features/rewards/mobile/boxMobile/__snapshots__/spec.tsx.snap, src/features/rewards/mobile/boxMobile/index.tsx, src/features/rewards/mobile/boxMobile/style.ts, src/features/rewards/walletSummary/__snapshots__/spec.tsx.snap, stories/features/rewards/settingsMobile/contributeBoxMobile.tsx, stories/features/rewards/settingsMobile/style.ts
Addresses the following:
https://github.com/brave/browser-android-tabs/issues/1134
https://github.com/brave/browser-android-tabs/issues/1140
https://github.com/brave/browser-android-tabs/issues/1095
https://brave-ui-2ei5lgk9l.now.sh
=> Front-end Android fixes

src/features/rewards/grantClaim/__snapshots__/spec.tsx.snap, src/features/rewards/grantClaim/index.tsx, src/features/rewards/grantClaim/style.ts, stories/features/rewards/settingsMobile/grantMobile.tsx
Related: https://github.com/brave/browser-android-tabs/issues/1148
Preview: https://media.giphy.com/media/9x4ZQsXQeU77coSMHp/giphy.gif
https://brave-ui-mbb9cr3l8.now.sh
=> Adding load spinner for mobile grant claim

src/features/rewards/panelWelcome/__snapshots__/spec.tsx.snap, src/features/rewards/panelWelcome/index.tsx, src/features/rewards/panelWelcome/style.ts, src/features/rewards/walletSummary/__snapshots__/spec.tsx.snap
Addresses https://github.com/brave/brave-browser/issues/3218
Button change from base subtle styling to white. Gave the bottom of the panel a little breathing room to match the top margin as well.
=> Increase contrast of join button in rewards join panel

src/components/formControls/select/style.ts, src/components/popupModals/modal/index.tsx, src/components/popupModals/modal/style.ts, src/features/rewards/mobile/boxMobile/__snapshots__/spec.tsx.snap, src/features/rewards/mobile/boxMobile/style.ts, src/features/rewards/rewardsButton/__snapshots__/spec.tsx.snap, src/features/rewards/rewardsButton/style.ts, src/features/rewards/walletPanel/__snapshots__/spec.tsx.snap, src/features/rewards/walletWrapper/__snapshots__/spec.tsx.snap, src/features/rewards/walletWrapper/style.ts, src/features/rewards/welcomePage/__snapshots__/spec.tsx.snap, stories/features/rewards/settingsMobile/contributeBoxMobile.tsx
Related:
https://github.com/brave/browser-android-tabs/issues/1136
https://github.com/brave/browser-android-tabs/issues/1018
https://github.com/brave/browser-android-tabs/issues/1004
https://github.com/brave/browser-android-tabs/issues/1147
https://brave-ui-7yrjrskra.now.sh
=> Android fixes (#1136, #1018, #1004, #1147)

src/features/rewards/walletPanel/__snapshots__/spec.tsx.snap, src/features/rewards/walletPanel/style.ts, src/features/rewards/walletSummary/__snapshots__/spec.tsx.snap, src/features/rewards/walletSummary/style.ts, src/features/rewards/walletSummarySlider/__snapshots__/spec.tsx.snap, src/features/rewards/walletSummarySlider/index.tsx, src/features/rewards/walletSummarySlider/style.ts, src/features/rewards/walletWrapper/__snapshots__/spec.tsx.snap, src/features/rewards/walletWrapper/style.ts, stories/features/rewards/concepts.tsx
Reverts brave/brave-ui#375
Only meant to approve
=> Revert "Making Rewards panel height dynamic"

src/features/rewards/walletPanel/__snapshots__/spec.tsx.snap, src/features/rewards/walletPanel/style.ts, src/features/rewards/walletSummary/__snapshots__/spec.tsx.snap, src/features/rewards/walletSummary/style.ts, src/features/rewards/walletSummarySlider/__snapshots__/spec.tsx.snap, src/features/rewards/walletSummarySlider/index.tsx, src/features/rewards/walletSummarySlider/style.ts, src/features/rewards/walletWrapper/__snapshots__/spec.tsx.snap, src/features/rewards/walletWrapper/style.ts, stories/features/rewards/concepts.tsx
Reverts brave/brave-ui#375
Only meant to approve
Reverting the revert
=> Revert "Revert "Making Rewards panel height dynamic""

package-lock.json, package.json, src/features/rewards/walletSummary/__snapshots__/spec.tsx.snap
Master seems to be broken atm. Noticed chatter on Slack and after doing the command specified, it fixed it. This is the result of running `npm i @storybook/addons --save-dev`
=> fix broken master

src/features/rewards/grantComplete/__snapshots__/spec.tsx.snap, src/features/rewards/grantComplete/index.tsx, src/features/rewards/grantComplete/style.ts, src/features/rewards/walletWrapper/index.tsx, src/features/rewards/walletWrapper/style.ts, stories/features/rewards/grant.tsx
Partial for https://github.com/brave/brave-browser/issues/4042
- 
=> Adds option to not display grant expiry date

src/features/rewards/grantComplete/__snapshots__/spec.tsx.snap, src/features/rewards/grantComplete/index.tsx, src/features/rewards/grantComplete/style.ts, src/features/rewards/walletSummary/__snapshots__/spec.tsx.snap, src/features/rewards/walletWrapper/index.tsx, src/features/rewards/walletWrapper/style.ts, stories/features/rewards/grant.tsx
Adds option to not display grant expiry date
- 
=> Expiry ads - 0.64

src/features/rewards/grantComplete/__snapshots__/spec.tsx.snap, src/features/rewards/grantComplete/index.tsx, src/features/rewards/grantComplete/style.ts, src/features/rewards/walletSummary/__snapshots__/spec.tsx.snap, src/features/rewards/walletWrapper/index.tsx, src/features/rewards/walletWrapper/style.ts, stories/features/rewards/grant.tsx
Adds option to not display grant expiry date
- 
=> Expiry ads - 0.63

src/features/shields/display.ts, src/features/shields/structure.ts, src/theme/shields-light.ts
=> meeting updates

src/features/rewards/profile/index.tsx, src/features/rewards/profile/style.ts, src/features/rewards/walletPanel/index.tsx, stories/assets/locale.ts, stories/features/rewards/concepts.tsx, stories/features/rewards/wallet.tsx
=> Unverified publishers in panel can now have status refreshed

src/features/rewards/walletWrapper/index.tsx, stories/assets/locale.ts, stories/features/rewards/concepts.tsx, stories/features/rewards/settings/pageWallet.tsx, stories/features/rewards/settingsMobile/mobileWalletPanel.tsx, stories/features/rewards/wallet.tsx
=> Adds text for ads grants

stories/assets/locale.ts
=> Updates locale text

src/features/welcome/images/welcome_search.svg, stories/features/welcome/page/fakeLocale.ts, stories/features/welcome/page/index.tsx, stories/features/welcome/page/screens/searchBox.tsx, stories/features/welcome/story.tsx
- Change flow for how users select their default search engine. Gives user ability to use immediate dropdown rather than go through settings
- https://github.com/brave/brave-browser/issues/1548
- Quick View:
- Ensure dropdown works
- Ensure 'Confirm' button still links to next page of on-boarding flow
- Ensure responsiveness on smaller screens
- http://localhost:9091/?path=/story/feature-components-welcome--page
- Third step of the onbording flow
Only change here that will be directly impacting brave-core will the the SVG update
https://github.com/brave/brave-core/pull/2479
=> Default search engine functional UI changes

src/features/rewards/siteBanner/index.tsx, src/features/rewards/siteBanner/style.ts
- https://brave-ui.nejczdovc.now.sh
=> Removes text from banner when custom bg image is set

src/features/rewards/modalAddFunds/__snapshots__/spec.tsx.snap, src/features/rewards/modalAddFunds/index.tsx, src/features/rewards/modalAddFunds/style.ts, src/features/rewards/walletWrapper/index.tsx, stories/features/rewards/modal.tsx, stories/features/rewards/settings/pageWallet.tsx
Uplift for https://github.com/brave/brave-browser/issues/4476
Original PR: #470 
- 
=> Add Funds modal now shows crypto selections centered

tools/icon-component-generator/package-lock.json, tools/icon-component-generator/package.json
we did a fork of https://github.com/balajmarius/svg2jsx which is now https://github.com/brave/svg2jsx.
commit sha including changes applied here are in https://github.com/brave/svg2jsx/commit/507bc7e3782f838fc28af639bfcd24bb4435a218
=> fix icon-component-generator vuln found by npm audit

src/features/rewards/walletPanel/index.tsx, src/features/rewards/walletPanel/style.ts, src/features/rewards/walletSummary/__snapshots__/spec.tsx.snap, stories/features/rewards/concepts.tsx
Reverts brave/brave-ui#489
The browser test `BraveRewardsBrowserTest.ProcessPendingContributions` is timing out.
=> Revert "don't show USD conversion in wallet monthly tip"

src/features/rewards/walletPanel/index.tsx, src/features/rewards/walletPanel/style.ts, stories/features/rewards/concepts.tsx
This reverts commit c7c5df2ef75149fe4668a455a7062621b8d097e1. (PR #489 and revert PR #494)
It seems that test failures were an unrelated fluke.
See #489 for more info.
=> Revert "Revert "don't show USD conversion in wallet monthly tip""

src/components/icons/fc-logo-vimeo.tsx, src/components/icons/index.tsx, src/features/rewards/profile/index.tsx, src/features/rewards/siteBanner/index.tsx, src/features/rewards/toggleTips/index.tsx, stories/features/rewards/other.tsx, stories/features/rewards/wallet.tsx
Related https://github.com/brave/brave-core/pull/2247
- 
=> Adds Vimeo support

src/features/newTab/default/index.ts, src/features/newTab/default/page/index.ts, src/features/newTab/default/settings/index.ts, src/features/newTab/toggle/index.tsx, src/features/newTab/toggle/style.ts, src/theme/brave-dark.ts, src/theme/brave-default.ts, src/theme/theme-interface.ts, stories/features/newTab/default.tsx, stories/features/newTab/default/footerInfo.tsx, stories/features/newTab/default/index.tsx, stories/features/newTab/default/settings.tsx, stories/features/newTab/fakeLocale.ts
PR https://github.com/brave/brave-ui/pull/485 was reverted in https://github.com/brave/brave-ui/pull/490. This PR undo the revert. 
Since there are breaking changes here this PR needs to land after approval of related brave-core PR.
Revert "Merge pull request #490 from brave/revert-485"
This reverts commit 82b3e981040b2ba89743108e6701f5fa24ce3b52, reversing
changes made to b0ec08cd4ed2a20401d058062f1c238fb9a67813.
=> Undo revert of https://github.com/brave/brave-ui/pull/485

package-lock.json
Resolves https://github.com/brave/brave-ui/issues/516
- 
=> Fixes npm audit

src/features/rewards/alert/index.tsx
Part of https://github.com/brave/brave-browser/issues/5501
=> Update rewards alert icon

src/features/rewards/walletPanel/index.tsx, stories/assets/locale.ts
https://brave-ui-h5s7mgld4.now.sh/?path=/story/feature-components-rewards-wallet-desktop--panel
- 
=> Adds new option for publisher status in the panel

src/features/rewards/siteBanner/index.tsx, stories/assets/locale.ts, stories/features/rewards/concepts.tsx
=> Adds connected notice to site banner

src/features/rewards/siteBanner/__snapshots__/spec.tsx.snap, src/features/rewards/siteBanner/index.tsx, src/features/rewards/siteBanner/style.ts
=> Adds verified check to the banner

src/features/rewards/walletPopup/__snapshots__/spec.tsx.snap, src/features/rewards/walletPopup/index.tsx, src/features/rewards/walletWrapper/index.tsx, stories/assets/locale.ts, stories/features/rewards/wallet.tsx
=> Adds detail view for connected wallet

src/features/rewards/modalRedirect/__snapshots__/spec.tsx.snap, src/features/rewards/modalRedirect/index.tsx, src/features/rewards/modalRedirect/style.ts, stories/features/rewards/modal.tsx
=> Adds option for custom button in redirect modal

src/features/rewards/walletWrapper/index.tsx, src/features/rewards/walletWrapper/style.ts
=> Removes disconnected overlay

src/features/rewards/walletWrapper/index.tsx, src/features/rewards/walletWrapper/style.ts
Related: https://github.com/brave/brave-browser/issues/5543
https://brave-ui-aszt1bwn8.now.sh
=> Making verified state background clear

.travis.yml, package-lock.json, package.json
Fixes: https://github.com/brave/brave-ui/issues/551
Test Plan:
Travis CI should fully pass
=> Fixing handlebars, other moderate/high vulnerabilities.

src/features/rewards/walletSummary/index.tsx
fixes https://github.com/brave/browser-android-tabs/issues/2397
It's Android change and we pull the Android branch directly
=> Fixes untranslated string on Android

src/theme/brave-dark.ts, src/theme/brave-default.ts, src/theme/theme-interface.ts
Needed for https://github.com/brave/brave-core/pull/4423/files
=> Add hover colors for context menu

src/components/layout/tabs/index.tsx
=> Fix type error in tabs component

package-lock.json, package.json
=> Update dev dependencies to fix audit errors

README.md
=> Typo in travis build README

src/theme/brave-dark.ts, src/theme/brave-default.ts, src/theme/theme-interface.ts
Resolves <https://github.com/brave/brave-ui/issues/584>
Added new colors 'excluding gradients' from the design team to the brave-default and brave-dark themes.
=> Added new colors to theme

src/theme/brave-dark.ts
Added brand variant for dark theme
- 
=> Added brand variant for dark theme

.github/workflows/codeql-analysis.yml
=> Set up automated CodeQL security scanning
