brave/brave-ui

- .gitignore
- .storybook/tsconfig.json
- .storybook/webpack.config.js
- src/features/rewards/panelSummary/__snapshots__/spec.tsx.snap
This add target dir for storybook when we are using it for development. This way it will not generate storybook files into the package folder.
> Fixes storybook start dir

- .gitignore
- Dockerfile
- now.json
- package.json
**Please do not merge until security review passes**
This provides config so that developers can simply run the `now` command inside the repo at any time and get a permanent public Url for that version that can be shared with other team members.
The main aim though is to have `now` create a public Url for each PR so that we can easily see the Storybook for the code in that PR. I've submitted a security review for that.
I decided to use docker so that we're serving a static version of storybook, instead of the hot-reload dev server. Save the trees.
Here's an example of a deployment: https://brave-ui-roywtrxoei.now.sh
> Get a Storybook for each PR via `now` deployments

- src/features/rewards/welcomePage/__snapshots__/spec.tsx.snap
- src/features/rewards/welcomePage/index.tsx
Need to grab DOM elements for testing. Added data-test-id to welcome page opt-in button.
> Added data-test-id for opt-in button testing

- src/components/index.ts
- src/components/layout/card/__snapshots__/spec.tsx.snap
- src/components/layout/card/index.tsx
- src/components/layout/card/spec.tsx
- src/components/layout/card/style.ts
- stories/components/layout.tsx
- stories/features/welcome/page/index.tsx
- stories/features/welcome/page/theme.ts
Added card component previously called panel. there's a component in rewards with the same name so I had to adapt. I like it tho.
Ideally, the rewards components should re-use it so one-change-changes-it-all but left them as-is for now. Welcome page was updated to make use of it.
> add card component

- .travis.yml
- package.json
By limiting `maxWorkers` to 4 we can greatly increase the speed of `test-unit-all`. Two examples:
https://travis-ci.org/brave/brave-ui/builds/422796662?utm_source=github_status&utm_medium=notification
https://travis-ci.org/brave/brave-ui/builds/422798386?utm_source=github_status&utm_medium=notification
> Fixing test-unit-all on Travis CI

- src/components/buttonsIndicators/button/__snapshots__/spec.tsx.snap
- src/components/buttonsIndicators/button/style.ts
- src/components/icons/index.tsx
- src/components/text/heading/__snapshots__/spec.tsx.snap
- src/components/text/heading/style.ts
- src/features/rewards/grantComplete/__snapshots__/spec.tsx.snap
- src/features/rewards/modalBackupRestore/__snapshots__/spec.tsx.snap
- src/features/rewards/panelWelcome/__snapshots__/spec.tsx.snap
- src/features/rewards/walletPanel/__snapshots__/spec.tsx.snap
- src/features/rewards/walletSummarySlider/__snapshots__/spec.tsx.snap
- src/features/rewards/walletWrapper/__snapshots__/spec.tsx.snap
- src/features/rewards/welcomePage/__snapshots__/spec.tsx.snap
- src/old/headings/__snapshots__/spec.tsx.snap
- src/old/headings/style.ts
> deprecate extend method

- src/features/rewards/modalContribute/index.tsx
- src/features/rewards/tableContribute/index.tsx
- stories/features/rewards/modal.tsx
- stories/features/rewards/table.tsx
Reverts PR #147 - removes sort prop from auto-contribute tables
> Reverting #147

- src/components/formControls/textarea/__snapshots__/spec.tsx.snap
- src/components/formControls/textarea/style.ts
- src/features/rewards/modalBackupRestore/__snapshots__/spec.tsx.snap
Fixes #130 
Fix confirmed on Ubuntu 18.04.1
> Fixes recovery key text area background on Linux

- src/features/rewards/box/__snapshots__/spec.tsx.snap
- src/features/rewards/box/index.tsx
- src/features/rewards/box/style.ts
A couple things should be checked here:
1. Showing/hiding the settings section on contribution and donation boxes should behave exactly the same.
2. The settings icon tooltip on those respective boxes should overflow and not clip in to the parent container.
> Removing flex transition for Box

- src/features/rewards/modalAddFunds/__snapshots__/spec.tsx.snap
- src/features/rewards/modalAddFunds/index.tsx
This PR resolves https://github.com/brave/brave-browser/issues/1414 by adding a `target="_blank"` to the FAQ link in the Add Funds modal.
To test:
- Navigate to the Add Funds page
- Click "FAQ"
- Observe the FAQ page opens in a new tab instead of navigating the current tab.
cc'ing @cezaraugusto as per the contributing page. Let me know if anything is out of order :)
Much love for this project <3
> Make "FAQ" link within "Add Funds" open a new tab

- src/components/buttonsIndicators/button/index.tsx
- src/features/rewards/modalBackupRestore/__snapshots__/spec.tsx.snap
- src/features/rewards/welcomePage/__snapshots__/spec.tsx.snap
Fix https://github.com/brave/brave-ui/issues/197
> only handle Button onClick once

- src/features/rewards/profile/__snapshots__/spec.tsx.snap
- src/features/rewards/profile/style.ts
- src/features/rewards/walletPanel/__snapshots__/spec.tsx.snap
> Fixes long publisher titles breaking out of wallet panel

- src/features/rewards/hero/__snapshots__/spec.tsx.snap
- src/features/rewards/hero/index.tsx
- src/features/rewards/hero/style.ts
- src/features/rewards/welcomePage/__snapshots__/spec.tsx.snap
- src/features/rewards/welcomePage/index.tsx
- src/features/rewards/welcomePage/style.ts
This includes a view small design tweaks targeted for mobile per design review:
1. Reduces the font size of the hero header/subtitle on smaller devices
2. On touchscreen devices removes the outer settings page wrapper/desktop header
3. Reduces hero padding for smaller devices
> Welcome page tweaks

- src/features/rewards/grantClaim/index.tsx
- src/features/rewards/grantClaim/style.ts
- src/features/rewards/grantWrapper/__snapshots__/spec.tsx.snap
- src/features/rewards/grantWrapper/index.tsx
- src/features/rewards/grantWrapper/style.ts
- src/features/rewards/mobile/walletInfoHeader/__snapshots__/spec.tsx.snap
- src/features/rewards/mobile/walletInfoHeader/index.tsx
- src/features/rewards/mobile/walletInfoHeader/style.ts
- src/features/rewards/modalAddFunds/index.tsx
- src/features/rewards/modalAddFunds/style.ts
- src/features/rewards/walletWrapper/index.tsx
- src/features/rewards/walletWrapper/style.ts
- stories/features/rewards/settingsMobile/grantMobile.tsx
- stories/features/rewards/settingsMobile/mobileWalletPanel.tsx
- stories/features/rewards/settingsMobile/settingsMobile.tsx
- stories/features/rewards/settingsMobile/style.ts
- stories/features/rewards/wallet.tsx
Storybook: https://brave-ui-fgfdeeypjd.now.sh
Unclaimed:
Claim Promp:
Mobile Wallet Summary: (After clicking on walletInfoHeader)
Add Funds view:
> Adding Grant claim/Wallet summary feature to Mobile Settings page

- src/features/rewards/mainToggle/__snapshots__/spec.tsx.snap
- src/features/rewards/mainToggle/index.tsx
Fixes #226 
Related to https://github.com/brave/brave-browser/issues/1723
> Combines disabled text strings

- src/features/rewards/settingsPage/__snapshots__/spec.tsx.snap
- src/features/rewards/settingsPage/style.ts
- src/features/rewards/welcomePage/__snapshots__/spec.tsx.snap
Fixes #230 
Related: https://github.com/brave/brave-browser/issues/1556
Before:
After:
> Enforces 1024px min-width for settingsPage

- src/features/rewards/panelWelcome/index.tsx
- src/features/rewards/panelWelcome/style.ts
- stories/features/rewards/concepts.tsx
Fixes #228 
Related to: https://github.com/brave/brave-browser/issues/1502
> Adds Wallet creation loader and failure message to panel opt in

- src/features/rewards/box/__snapshots__/spec.tsx.snap
- src/features/rewards/box/style.ts
- ~header top padding~
- darker description
- ~toggle~
> tweaks on rewards

- src/features/rewards/tooltip/__snapshots__/spec.tsx.snap
- src/features/rewards/tooltip/index.tsx
- src/features/rewards/tooltip/style.ts
- stories/features/rewards/settings/contributeBox.tsx
Fixes: https://github.com/brave/brave-browser/issues/1850
Basically, the mouse intent area was too large, making it possible through quick movements to persist the tooltip, and block site exclude actions.
This reduces the mouse area to just the `children` of `<Tooltip>`, leaving functionality as expected and this bug not reproducible.
> Fixes tooltip persistence issue for site exclude

- src/features/rewards/tableDonation/index.tsx
> Fixes token amount in donation table

- src/features/rewards/index.ts
- src/features/rewards/modalContribute/index.tsx
- src/features/rewards/modalContribute/style.ts
- src/features/rewards/restoreSites/__snapshots__/spec.tsx.snap
- src/features/rewards/restoreSites/index.tsx
- src/features/rewards/restoreSites/spec.tsx
- src/features/rewards/restoreSites/style.ts
- src/features/rewards/tableContribute/index.tsx
- src/features/rewards/tableContribute/style.ts
- stories/assets/locale.ts
- stories/features/rewards/settings/contributeBox.tsx
Related: https://github.com/brave/brave-browser/issues/1883
Since code would have to be duplicated to include this in `TableContribute`, I refactored the restore sites prompt in to its own component.
Pictured here on the `TableContribute` component under `Box`:
Note ^^ as this prompt is hidden on the outer view when "Show All" is present, you won't see it like this in the storybook. You may view the component in the contribute modal by clicking "Show All" in the event of 5 or few sites, this will be visible on the outer view.
> Adding RestoreSites component

- src/features/rewards/walletWrapper/style.ts
> Reduces alert close icon size

- src/features/rewards/walletPanel/index.tsx
- stories/features/rewards/concepts.tsx
- stories/features/rewards/wallet.tsx
Fixes: #291 
To be used by: https://github.com/brave/brave-core/pull/957
Before (`monthlyAmount={10}`)
After (`monthlyAmount={'10.0'}`)
> Changing monthlyAmount prop to string

- src/features/rewards/walletWrapper/index.tsx
This is associated with brave/brave-browser#1479.
Adds support for "insufficient funds" notifications in Rewards, which is sent when the current balance is insufficient to make new contributions.
> Add support for insufficientFunds notification

- src/features/rewards/amount/index.tsx
- src/features/rewards/donate/index.tsx
- src/features/rewards/siteBanner/index.tsx
- src/features/rewards/tip/index.tsx
- stories/features/rewards/concepts.tsx
- stories/features/rewards/other.tsx
Fixes: https://github.com/brave/brave-ui/issues/298
This is what involved in fixing the integration test error in the issue. It seems that there was further inconsistency in amount typing even after the work done https://github.com/brave/brave-ui/pull/194
Everything works in the UI as far as I have tested, (Balance calculation works, and expected error will come up if you select a token amount that exceeds your wallet balance
> Uses string type for amount/tokens

- src/features/rewards/walletWrapper/index.tsx
This is associated with brave/brave-browser#1164.
Adds support for "backup wallet" notifications in Rewards, which is sent when the user needs to backup their wallet.
> Add support for backupWallet notification

- src/features/rewards/mobile/mainToggleMobile/__snapshots__/spec.tsx.snap
- src/features/rewards/mobile/mainToggleMobile/style.ts
Related: https://github.com/brave/browser-android-tabs/issues/914
Fix at small (320px) viewport: (Text wrapping was agreed upon)
Fix at larger, but still slim 375px viewport:
> Fixing rewards toggle for long translations

- src/features/rewards/walletWrapper/index.tsx
Fixes the issue mentioned here: https://github.com/brave/brave-core/pull/1092#pullrequestreview-185459333
Simply captures the grant status in a variable called `status`
Problem was that `status` here was undefined: https://github.com/brave/brave-ui/blob/master/src/features/rewards/walletWrapper/index.tsx#L215
- 
> Captcha wrong position status fix

- src/features/rewards/grantWrapper/__snapshots__/spec.tsx.snap
- src/features/rewards/grantWrapper/style.ts
- src/features/rewards/walletWrapper/style.ts
Adjusts close icon size, grant claim icon alignment on notification, small grant claim button adjustment
https://brave-ui-j53nddfrk.now.sh
Changes can be verified in the storybook
- 
> Fixing grant claim icon alignment

- src/features/rewards/grantCaptcha/__snapshots__/spec.tsx.snap
- src/features/rewards/grantCaptcha/style.ts
- src/features/rewards/grantWrapper/style.ts
A couple of stylistic changes to ensure that the captcha drop image is not clipped, as is the case when drop targets are closer to the bottom of the image.
Before on `brave-core` feature:
After on `brave-core` feature:
View changes: https://brave-ui-12tmvvviv.now.sh
- 
> Fixes captcha target clipping issue

- src/features/newTab/stats/style.ts
- src/old/clock/style.ts
Remaining minor style tweaks still located in Brave UI related to https://github.com/brave/brave-core/pull/1091. 
- color updates to a more current brand palette
- enlarged the clock typeface
- omitted the time period
- general padding tweaks
> Remaining NTP Updates

- src/features/sync/grid/index.ts
address https://github.com/brave/brave-browser/issues/2676
1. Go to Sync and `Enabled Content` screen
2. Check that `bookmarks` toggle only contains 1 row
- n/a
> make switch toggle grid with only 1 row

- src/features/rewards/donationOverlay/index.tsx
- src/features/rewards/donationOverlay/style.ts
- stories/features/rewards/other.tsx
Related: https://github.com/brave/brave-browser/issues/2668
Adds support custom publisher logo in the donationOverlay component. Implementation and styling is similar to how it is in siteBanner.
Please view the donationOverlay concept in Rewards > Other in the provided storybook (https://brave-ui-4ty18cf5o.now.sh)
This is the knob configuration for getting the custom logo to show:
Preview: 
- 
- When uplift-approved, merge to brave-core-0.60.x feature branch
> Allows for custom publisher logo in donationOverlay

- src/features/rewards/walletPanel/index.tsx
- src/features/rewards/walletPanel/style.ts
- src/features/rewards/walletSummary/index.tsx
- src/features/rewards/walletSummary/style.ts
- src/features/rewards/walletWrapper/__snapshots__/spec.tsx.snap
- src/features/rewards/walletWrapper/style.ts
- stories/assets/locale.ts
- stories/features/rewards/wallet.tsx
- adds info about reserved funds in wallet summary
- removes change setting button from the panel
- https://brave-ui-drej78cr4.now.sh
> Adds reserved amount to wallet summary

- src/features/rewards/walletSummary/__snapshots__/spec.tsx.snap
- src/features/rewards/walletSummary/index.tsx
- stories/assets/locale.ts
- changes locale to be unique so that doesn't mess up notification title
- 
> Fixes locale mix

- src/components/popupModals/modal/index.tsx
- src/components/popupModals/modal/style.ts
- src/features/rewards/list/__snapshots__/spec.tsx.snap
- src/features/rewards/list/style.ts
- src/features/rewards/modalAddFunds/index.tsx
Related issues:
https://github.com/brave/browser-android-tabs/issues/1017
https://github.com/brave/browser-android-tabs/issues/984
Reduces the maximum height for modals on android to accommodate for menu bars, increasing right hand column size for small viewports in rewards settings views
https://brave-ui-eqkrfzj48.now.sh
Simulates viewport and menu from the pixel 3 xl in the issue (fix pictured)
- 
> Various Android fixes

- src/features/rewards/mobile/boxMobile/index.tsx
Related: https://github.com/brave/browser-android-tabs/issues/1093
The view was incorrectly showing `children` instead of what is passed through `settingsChild`
Before:
After:
https://brave-ui-bjbyvybmh.now.sh
> Showing settings child in settings pane

- src/features/rewards/mobile/boxMobile/__snapshots__/spec.tsx.snap
- src/features/rewards/mobile/boxMobile/style.ts
Related:
https://github.com/brave/browser-android-tabs/issues/1094
https://github.com/brave/browser-android-tabs/issues/1090
I'm not sure exactly when or why this broke, but this needed readjusting. It should look good at all mobile viewports now.
https://brave-ui-jjtd75e7l.now.sh
Before: 
After:
> Fixes mobile settings header

- src/features/rewards/settingsPage/__snapshots__/spec.tsx.snap
- src/features/rewards/settingsPage/index.tsx
- src/features/rewards/settingsPage/style.ts
- src/features/rewards/welcomePage/__snapshots__/spec.tsx.snap
Now that Brave-Core has its own Navigation Bar (implemented in https://github.com/brave/brave-core/pull/1422), we can remove the temporary reserved area from the Rewards Views.
Required for https://github.com/brave/brave-browser/issues/956
Removed Header from Rewards Settings (desktop) page.
Rewards settings desktop 
- 
> Rewards on Desktop: Remove temporary header

- src/features/rewards/walletWrapper/index.tsx
- src/features/rewards/walletWrapper/style.ts
- stories/assets/locale.ts
- stories/features/rewards/concepts.tsx
Related issue: https://github.com/brave/brave-browser/issues/2739
This partially implements changes from this PR: https://github.com/brave/brave-ui/pull/346
This also generalizes the notification action via `onNotificationClick`
https://brave-ui-ql7hj2fsk.now.sh
> Adds action to backup wallet notification

- package-lock.json
- package.json
- src/features/rewards/mobile/boxMobile/index.tsx
Upgrades Jest, resolves `npm audit` advisories.
https://brave-ui-3dqrimz7v.now.sh
> Upgrading jest to 24.1.0, fixing npm audit

- src/features/newTab/default/topSites/index.ts
Addresses https://github.com/brave/brave-browser/issues/3487
The `href` was on the `img` so this just pads the clickable area to assume more of the space of the tile behind the pin and bookmark icons.
> update topsite tile click area

- src/features/rewards/box/__snapshots__/spec.tsx.snap
- src/features/rewards/box/index.tsx
- src/features/rewards/box/style.ts
Addresses: https://github.com/brave/brave-browser/issues/3483
Color matches the other implemented close icons.
> Tweak close icons in Rewards setting box

- src/features/rewards/mobile/index.ts
- src/features/rewards/mobile/selectMobile/__snapshots__/spec.tsx.snap
- src/features/rewards/mobile/selectMobile/index.tsx
- src/features/rewards/mobile/selectMobile/spec.tsx
- src/features/rewards/mobile/selectMobile/style.ts
- stories/features/rewards/settingsMobile/contributeBoxMobile.tsx
Functionality for the new component should be in parity with the `Select` that we have been using.
For mobile it is important that the genuine `<select><option>..</select>` is used so mobile selector comes up when it is time to change options.
Related android issues:
https://github.com/brave/browser-android-tabs/issues/1234
https://github.com/brave/browser-android-tabs/issues/1202
https://github.com/brave/browser-android-tabs/issues/1133
https://brave-ui-asrpecz3f.now.sh
> Adding selectMobile component

- stories/components/theme.tsx
Just some general storybook polish. No issue tied to this one. Added a hex value to the cards. Removed the chapters addon reference as we are going to move to documentation outside of storybook in some capacity.
> Update theme story styling

- src/features/rewards/walletEmpty/index.tsx
- src/features/rewards/walletEmpty/style.ts
- stories/assets/locale.ts
- stories/features/rewards/settingsMobile/mobileWalletPanel.tsx
Related: https://github.com/brave/browser-android-tabs/issues/1315
https://brave-ui-cifavwm5h.now.sh
> Adding hideAddFundsText prop to WalletEmpty

- src/components/formControls/checkbox/index.tsx
- src/features/rewards/grantClaim/index.tsx
- src/features/rewards/grantComplete/index.tsx
- src/features/rewards/grantWrapper/index.tsx
- src/features/rewards/siteBanner/index.tsx
- src/features/rewards/tableContribute/index.tsx
- src/features/rewards/walletWrapper/index.tsx
Fixes #417
This adds several `data-test-id` attributes required by the Rewards browser tests.
It's a prerequisite for brave/brave-browser#3161.
> Add data-test-id attributes for Rewards testing

- src/features/rewards/walletPanel/__snapshots__/spec.tsx.snap
- src/features/rewards/walletPanel/style.ts
- src/features/rewards/walletSummary/__snapshots__/spec.tsx.snap
- src/features/rewards/walletSummary/style.ts
- src/features/rewards/walletSummarySlider/__snapshots__/spec.tsx.snap
- src/features/rewards/walletSummarySlider/index.tsx
- src/features/rewards/walletSummarySlider/style.ts
- src/features/rewards/walletWrapper/__snapshots__/spec.tsx.snap
- src/features/rewards/walletWrapper/style.ts
- stories/features/rewards/concepts.tsx
Related issue: https://github.com/brave/brave-browser/issues/2874
The panel should now accommodate all levels of content.
https://brave-ui-41sbv9idu.now.sh
> Making Rewards panel height dynamic

- src/features/shields/display.ts
- src/features/shields/structure.ts
* do not add opacity to shields row text when disabled
* do not wrap urls with queries in static list
* allow selection of blocked resources in the static list
* trim long site names
`now` link with changes: https://brave-ui-9qm8j8br4.now.sh
> Shields improvements

- src/features/rewards/walletWrapper/index.tsx
- stories/assets/locale.ts
Related: https://github.com/brave/brave-browser/issues/3637
Core PR: https://github.com/brave/brave-core/pull/1959
- 
> Adding notification type for tips being processed

- src/features/rewards/boxAlert/__snapshots__/spec.tsx.snap
- src/features/rewards/boxAlert/index.tsx
- src/features/rewards/boxAlert/spec.tsx
- src/features/rewards/boxAlert/style.ts
- src/features/rewards/index.ts
- stories/assets/locale.ts
- stories/features/rewards/settings/adsBox.tsx
- stories/features/rewards/settings/donationsBox.tsx
Related issue: https://github.com/brave/brave-browser/issues/2562
The tips alert component was too specific, now it is more general, and we can add a flavor for auto contribute now if needed.
https://brave-ui-dmhift3yt.now.sh
- 
> Changing tipsMigrationAlert -> boxAlert, adding Ads variant

- src/features/rewards/rewardsButton/__snapshots__/spec.tsx.snap
- src/features/rewards/rewardsButton/index.tsx
- src/features/rewards/rewardsButton/style.ts
- src/features/rewards/walletPanel/__snapshots__/spec.tsx.snap
- src/features/rewards/walletPanelDisabled/__snapshots__/spec.tsx.snap
- src/features/rewards/welcomePage/__snapshots__/spec.tsx.snap
Addresses: https://github.com/brave/brave-browser/issues/3904
The att name in this case just needed to be different than the component's prop name
By navigating to the wallet panel concept, confirm the console error in the above issue does not show.
https://brave-ui-m1yk2rzha.now.sh
> Fixing panel console error

- src/features/rewards/walletPanel/style.ts
Related: https://github.com/brave/brave-browser/issues/3930
You should not see the scrollbar in storybook on MacOS now if you have your preferences set to always show scroll bars.
https://brave-ui-n12kj8qp7.now.sh
> Using overflow-y: auto for unverified notice

- src/features/rewards/profile/index.tsx
- src/features/rewards/profile/style.ts
- src/features/rewards/walletPanel/index.tsx
- src/features/rewards/walletSummary/__snapshots__/spec.tsx.snap
- stories/assets/locale.ts
- stories/features/rewards/concepts.tsx
- stories/features/rewards/wallet.tsx
Addresses https://github.com/brave/brave-browser/issues/3339
Added 'Check again...' link to check for publisher's verified status
Open unverified wallet panel, verify 'Check again...' link
- https://storybook-out.jasonrsadler.now.sh?path=/story/feature-components-rewards-wallet-desktop--panel
> Unverified publishers in panel can now have status refreshed

- src/features/rewards/walletPanel/__snapshots__/spec.tsx.snap
- src/features/rewards/walletPanel/index.tsx
- src/features/rewards/walletPanel/style.ts
- stories/features/rewards/concepts.tsx
Using plain `<select>` for WalletPanel to avoid clipping issues. Should maintain the look and feel of the previous component.
https://brave-ui-gz4ablrx5.now.sh
> Using HTML select for walletPanel

- src/features/rewards/walletSummary/__snapshots__/spec.tsx.snap
- src/features/shields/select/index.ts
Test Plan:
Ensure dropdowns on Shields have visible text across platforms
Now link: https://brave-ui-e45cj4qm1.now.sh
> Fix dropdown colors for Shields in Windows

- src/features/newTab/default/grid/index.ts
- Change margins for clock and stats widgets so RTL is supported (Addresses Issue: https://github.com/brave/brave-browser/issues/3574)
- Quick View:
- Launch brave while system locale is LTR (English), and RTL (Arabic, Hebrew)
- Open new tabs page and widgets should not be flush with edge
- Resize window to check for responsive behavior
- Manually edit enclosing html for `new tabs page` feature with attribute `dir="rtl"`
- http://localhost:9091/?path=/story/feature-components-new-tab-default--page
> Fix New Tabs Page display for RTL Languages

- src/features/rewards/welcomePage/__snapshots__/spec.tsx.snap
- src/features/rewards/welcomePage/index.tsx
- stories/assets/locale.ts
Related: https://github.com/brave/brave-browser/issues/4489
Changed service text to match the text on button.
https://brave-ui-mfe6xww2v.now.sh
> Service text ready

- stories/features/sync/page/fakeLocale.ts
Updating the usage of the verb
- `e` swapped in for `a`
- Only if string matching breaks downstream screen validation. Could not find any other references, as such should have no impact on test validity
- See [affect vs effect](https://en.oxforddictionaries.com/usage/affect-or-effect) in the Oxford Dictionary
> Grammatical Correction

- src/components/layout/card/__snapshots__/spec.tsx.snap
- src/components/layout/card/index.tsx
- src/components/layout/card/spec.tsx
- src/components/layout/card/style.ts
- src/features/rewards/box/__snapshots__/spec.tsx.snap
- src/features/rewards/box/index.tsx
- src/features/rewards/box/style.tsx
- src/features/rewards/disabledBox/__snapshots__/spec.tsx.snap
- src/features/rewards/disabledBox/style.ts
- src/features/rewards/mobile/boxMobile/__snapshots__/spec.tsx.snap
- src/features/rewards/mobile/boxMobile/index.tsx
- src/features/rewards/mobile/boxMobile/style.tsx
- src/features/sync/index.ts
- src/features/sync/misc/index.tsx
- src/features/welcome/wrapper/index.ts
- stories/features/sync/disabledContent.tsx
- stories/features/sync/enabledContent.tsx
- tsconfig.json
These css overrides would prevent Card from ever changing structure, or in fact any aspect of its design.
Impetus is to create a built-in alert style, but even if we don't go down that direction, it is necessary.
Everything should look exactly the same
- https://brave-ui-3bt6h5km9.now.sh
> Remove css overrides for Card component

- src/features/rewards/modalAddFunds/__snapshots__/spec.tsx.snap
- src/features/rewards/modalAddFunds/index.tsx
- src/features/rewards/modalAddFunds/style.ts
- src/features/rewards/walletWrapper/index.tsx
- stories/features/rewards/modal.tsx
- stories/features/rewards/settings/pageWallet.tsx
- stories/features/rewards/table.tsx
Part of https://github.com/brave/brave-browser/issues/4476
Centers crypto selections in Add Funds modal
- 
> Add Funds modal now shows crypto selections centered

- src/features/rewards/tableContribute/index.tsx
Adds data-test-id to tableContribute row anchor to identify row links for testing
- 
> Adds data-test-id to tableContribute row anchor

- src/features/newTab/default/index.ts
- src/features/newTab/default/page/index.ts
- src/features/newTab/default/settings/index.ts
- src/features/newTab/toggle/index.tsx
- src/features/newTab/toggle/style.ts
- src/features/rewards/walletSummary/__snapshots__/spec.tsx.snap
- src/theme/brave-dark.ts
- src/theme/brave-default.ts
- src/theme/theme-interface.ts
- stories/features/newTab/default.tsx
- stories/features/newTab/default/footerInfo.tsx
- stories/features/newTab/default/index.tsx
- stories/features/newTab/default/settings.tsx
- stories/features/newTab/fakeLocale.ts
Feature Spec: https://github.com/brave/brave-browser/issues/4523
- Add a new "Settings" Icon at the foot of the page
- Clicking the icon will bring up a menu with one toggle option
- Clicking the toggle will change the background to be an image (with a description at the footer versus a gradient background)
- Dark mode will bring up a different system menu
Quick view:
Go to storybook and make the following assertions:
1. Ensure menu is toggle-able and exits upon outside click
2. Ensure background is toggle-able from within the menu option
3. Ensure responsiveness (super small screens specs TBD)
4. Ensure app supports dark mode (see knobs)
http://localhost:9091/?path=/story/feature-components-new-tab-default--page
https://brave-ui.imptrx.now.sh/?path=/story/feature-components-new-tab-defaul …
> Change Background Settings for New Tabs Page

- src/features/rewards/amount/__snapshots__/spec.tsx.snap
- src/features/rewards/amount/index.tsx
- src/features/rewards/donate/__snapshots__/spec.tsx.snap
- src/features/rewards/donate/index.tsx
- src/features/rewards/grantComplete/__snapshots__/spec.tsx.snap
- src/features/rewards/grantComplete/index.tsx
- src/features/rewards/listToken/index.tsx
- src/features/rewards/profile/index.tsx
- src/features/rewards/siteBanner/__snapshots__/spec.tsx.snap
- src/features/rewards/tip/__snapshots__/spec.tsx.snap
- src/features/rewards/walletSummary/__snapshots__/spec.tsx.snap
- src/features/rewards/walletSummary/index.tsx
- src/features/rewards/walletWrapper/index.tsx
Needed in https://github.com/brave/brave-core/pull/2512
- 
> Adds Add Funds button to the notification

- src/features/welcome/button/index.ts
- src/features/welcome/index.ts
- stories/features/welcome/page/screens/footerBox.tsx
- stories/features/welcome/page/screens/importBox.tsx
- stories/features/welcome/page/screens/rewardsBox.tsx
- stories/features/welcome/page/screens/searchBox.tsx
- stories/features/welcome/page/screens/themeBox.tsx
- stories/features/welcome/page/screens/welcomeBox.tsx
Addresses https://github.com/brave/brave-browser/issues/4658
This one is just a revision of the black focus squares we have going on in the default buttons at the moment. This can be reverted when the shared button component is more thoroughly defined.
These changes will have to happen in large part (I believe) in Core repo. The styling approach took into consideration the theming update in the neighboring PR.
> Button focus styling

- src/features/rewards/walletPanel/index.tsx
- src/features/rewards/walletPanel/style.ts
- src/features/rewards/walletSummary/__snapshots__/spec.tsx.snap
- stories/features/rewards/concepts.tsx
Fixes brave/brave-browser#4503.
In the wallet panel, don't show the USD conversion and fix clipping of BAT values.
1. Enable Brave Rewards from a clean profile, add tokens
1. Navigate to a site such as brave.com
1. Bring up the wallet panel.
1. Click "Send Tip" and make a monthly donation (mark "Make this monthly")
1. Re-open the wallet panel
1. Check to make sure the shown tip amount is correct, and it is not clipped and there is no text after "BAT"
1. Change monthly contribution amount to a different amounts than the recurring tip, and check the same as above
1. Close and re-open panel
1. Confirm that the value set in step 7 persists
1. Confirm that setting a monthly amount of 0.0 removes the donation from the table.
- https://brave-ui.ccooper1.now.sh/?path=/story/feature-components-rewa …
> don't show USD conversion in wallet monthly tip

- src/features/newTab/default/grid/index.ts
- src/features/newTab/default/settings/index.ts
- src/features/newTab/default/topSites/index.ts
Issue: https://github.com/brave/brave-browser/issues/5038
Technicals Description:
- Currently users with very high stats numbers make the stats element bigger. In conjunction with margins on the widget themselves, overflow is created on NTP.
- Vertical scroll bars appear because horizontal scroll bars take up page space
Quick view:
- Adjust media query margins to be larger to account for margins and scroll bars
- Open New tabs page
- Slowly shrink window and see if horizontal/vertical scroll bars appear
- Note: Beyond a certain size, shrinking will always produce vertical scroll bars since the page physically doesn't fit the elements
- https://brave-ui-mbnub1i2y.now.sh/?path=/story/feature-components-new-tab-default--page
https://github.com/brave/brave-core/pull/2826
- When …
> Adjust media query boundaries to account for large stats and margins

- src/features/newTab/default/clock/index.tsx
- src/features/newTab/default/grid/index.ts
- src/features/newTab/default/index.ts
- src/features/newTab/default/settings/index.ts
- src/features/newTab/default/topSites/index.ts
- src/features/newTab/default/widget/index.tsx
- src/features/newTab/default/widget/styles.ts
- stories/features/newTab/default/index.tsx
- stories/features/newTab/default/settings.tsx
- stories/features/newTab/default/stats.tsx
- stories/features/newTab/default/topSites/topSitesList.tsx
- stories/features/newTab/fakeLocale.ts
Spec: https://github.com/brave/brave-browser/issues/4510
- Added more options in the settings menu to toggle the showing of widgets
- Each of the three widgets (Stats, Clock, TopSites) will show/hide from the menu
- Quick View:
- Ensure menu opens and closes properly
- Ensure widgets display properly independently of whether the other widgets are being shown
- Ensure widgets can toggle from the menu
- https://brave-ui.imptrx.now.sh/?path=/story/feature-components-new-tab-default--page
https://github.com/brave/brave-core/pull/2762
> Toggle widgets NTP

- src/features/rewards/mobile/boxMobile/index.tsx
Related: https://github.com/brave/browser-android-tabs/issues/1858
Going back from `settings (ex: rewards/ads-settings) -> detailView (ex: rewards/ads)` was not working as expected when pushing the Android back button. Entries in the history state are fine, there was just a boolean logic problem when doing so.
> Fixing detail view and settings page logic error (boxMobile) [Android]

- src/features/welcome/images/index.ts
- src/features/welcome/images/welcome_bg.svg
- src/features/welcome/images/welcome_import.svg
- src/features/welcome/images/welcome_rewards.svg
- src/features/welcome/images/welcome_search.svg
- src/features/welcome/images/welcome_shields.svg
- src/features/welcome/images/welcome_theme.svg
- src/features/welcome/text/index.ts
- src/features/welcome/wrapper/index.ts
- src/theme/welcome-dark.ts
- src/theme/welcome-light.ts
- stories/features/welcome/page/index.tsx
- stories/features/welcome/story.tsx
Addresses: https://github.com/brave/brave-browser/issues/4657
Addresses: https://github.com/brave/brave-browser/issues/3911
Now: https://brave-ui-en211eort.now.sh
> Welcome dark theme

- stories/features/welcome/page/fakeLocale.ts
- stories/features/welcome/page/screens/themeBox.tsx
Spec: https://github.com/brave/brave-browser/issues/4992
Quick View:
- inline option to select theme during onboarding
- go to brave://welcome
- at the 4th screen during the on-boarding process you now have a dropdown to select theme
- button is disabled unless a valid option is selected
- clicking the confirm should go to next screen
- https://brave-ui-iwtuqykho.now.sh/?path=/story/feature-components-welcome--page
> ✨ Inline theme selection at on-boarding

- src/features/shields/display.ts
- src/features/shields/structure/index.ts
- src/theme/brave-dark.ts
- src/theme/shields-dark.ts
- stories/features/shields/components/advancedView/header.tsx
- stories/features/shields/components/advancedView/index.tsx
- stories/features/shields/components/simpleView/header.tsx
- stories/features/shields/components/simpleView/index.tsx
- stories/features/shields/fakeLocale.ts
- stories/features/shields/index.tsx
- stories/features/shields/story.tsx
DisabledContentView now has a vertical layout to support the "Report a broken site" button in accordance with mockups in https://github.com/brave/brave-browser/issues/4262.
The default dark and shields dark themes were also updated to support showing the new report button in dark mode.
Required for https://github.com/brave/brave-core/pull/3420.
Storybook was updated to reflect the new DisabledContentView and its contents.
- http://localhost:9091/?path=/story/feature-components-shields--panel
> update DisabledContentView to support reporting broken sites

- src/theme/index.tsx
This allows `ThemedStyledComponentsModule` to receive any theme as a prop. Needed for https://github.com/brave/brave-core/pull/3300.
The reasoning I had is that we can type feature-specific themes in there instead of forcing a theme in root level. I'm open for discussion regarding better options.
> allow any kind of theme for themeProvider and helper methods

- src/components/layout/card/__snapshots__/spec.tsx.snap
- src/components/layout/card/style.ts
- src/theme/brave-dark.ts
This adds some generic color overrides that should be useful for most browser components in dark mode: text, panel colors, and button colors.
I've tweaked the `Card` component to use the `panelBackground` theme color since it's also required to be able to theme the webcompat reporter dialog.
- 
> Make dark theme more useful

- src/components/formControls/select/index.tsx
Resolves #560
Currently, the rendered node corresponding to the selected option is stored in state and then used during render. This means that we can be displaying a react node that no longer corresponds to one of the select component's children. Instead of storing the rendered node in state, simply recompute the "selected" node on each render.
- 
> Don't store currently selected option ReactNode in state

- package.json
- src/helpers.test.ts
- src/helpers.ts
When upgrading Brave to Chromium 90 message replacement patterns were changed from using curly braces to square brackets. This change adds support for square bracket message patterns. Eventually all messages should be reconfigured to use appropriate placeholders instead of delimited patterns.
- 
> Update getLocale to support square-bracket replacement patterns

- package-lock.json
- package.json
- package/package.json
- src/components/buttonsIndicators/button/style.ts
- src/old/contentToggleArrow/style.ts
- src/old/dataBlock/index.tsx
- src/old/dataBlock/style.ts
- src/old/headings/index.tsx
- src/old/headings/style.ts
- src/old/index.ts
- src/old/mediaContent/style.ts
- src/old/page/style.ts
- src/old/paragraph/index.tsx
- src/old/paragraph/style.ts
- src/old/pushButton/style.ts
- src/old/switchButton/__snapshots__/spec.tsx.snap
- src/old/switchButton/index.tsx
- src/old/switchButton/style.ts
- src/old/textLabel/style.ts
- src/old/unstyledButton/index.tsx
- src/old/unstyledButton/style.ts
storybook / tsc inside brave-ui wasn't complaining about these issues, nor was brave-core complaining when brave-ui was included via `npm link brave-ui`. But brave-core _is_ complaining when used as regular npm -> github dependency. So, here we are...
> styled-components fixes

- src/components/formControls/checkbox/__snapshots__/spec.tsx.snap
- src/components/formControls/checkbox/index.tsx
- src/components/formControls/checkbox/spec.tsx
Tabindex should be number, not string. Fixes brave-core typescript errors when integrating https://github.com/brave/brave-ui/pull/595
unit tests still pass
- 
> checkbox: fix tabindex should be number, not string
